apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-quarkus
spec:  
  template:
    spec:
      containers:
      - name: hello-quarkus
        env:
        - name: GREETING
          value: "localz only"
