apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
spec:  
  template:
    spec:
      containers:
      - name: sample-app
        env:
        - name: GREETING
          value: "localz only"
